FROM node:20-alpine AS builder
WORKDIR /app

# Accept API base URL at build time so Vite can bake it in
ARG VITE_API_BASE_URL
ARG VITE_PRICE_WINDOW_PAST_HOURS=4
ARG VITE_PRICE_WINDOW_FUTURE_HOURS=10
ARG VITE_PROPERTIES_POLL_MS=10000
ARG VITE_PRICES_POLL_MS=300000

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_PRICE_WINDOW_PAST_HOURS=$VITE_PRICE_WINDOW_PAST_HOURS
ENV VITE_PRICE_WINDOW_FUTURE_HOURS=$VITE_PRICE_WINDOW_FUTURE_HOURS
ENV VITE_PROPERTIES_POLL_MS=$VITE_PROPERTIES_POLL_MS
ENV VITE_PRICES_POLL_MS=$VITE_PRICES_POLL_MS

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
